---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "false"
spec:
  releaseName: prom-operator
  forceUpgrade: true
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.3.0
  values:
    defaultRules:
      create: true
      rules:
        alertmanager: false
        etcd: true
        general: true
        k8s: true
        kubeApiserver: true
        kubePrometheusNodeAlerting: true
        kubePrometheusNodeRecording: true
        kubernetesAbsent: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeScheduler: true
        network: true
        node: true
        prometheus: true
        prometheusOperator: true
        time: true

    prometheus:
      ingress:
        enabled: false

    kubelet:
      serviceMonitor:
        https: false

    alertmanager:
      ingress:
        enabled: false

    grafana:
      enabled: true
      plugins:
        - grafana-kubernetes-app
        - camptocamp-prometheus-alertmanager-datasource
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          kubernetes-pod-monitoring:
            gnetId: 9144
            revision: 2
            datasource: Prometheus
          Kubernetes-Deployment-Statefulset-Daemonset-metrics:
            gnetId: 8588
            revision: 1
            datasource: Prometheus
          Cluster-Monitoring-for-Kubernetes:
            gnetId: 10000
            revision: 1
            datasource: Prometheus
          Cluster-cost:
            gnetId: 8670
            revision: 5
            datasource: Prometheus
          Cluster-Dashboard:
            gnetId: 11358
            revision: 1
          Jenkins:
            gnetId: 9964
            revision: 1
            datasource: Prometheus
          NodeLocalDNS:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/nodelocaldns.json
          CoreDNS-Cluster:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/coredns_cluster.json
          FluxPerf:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/flux-performance.json
          AppHealth:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/app_health.json
          Kuberhealthy:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/kuberhealthy.json
          AdminApps:
            url: https://raw.githubusercontent.com/hmcts/prometheus-monitoring/master/grafana/dashboards/admin_health.json