---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prom-operator
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "false"
spec:
  releaseName: prom-operator
  forceUpgrade: true
  rollback:
    enable: true
    retry: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 8.3.0

  grafana:
    enabled: false
    plugins:
      - grafana-kubernetes-app
      - camptocamp-prometheus-alertmanager-datasource
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-pod-monitoring:
          gnetId: 9144
          revision: 2
          datasource: Prometheus
        Kubernetes-Deployment-Statefulset-Daemonset-metrics:
          gnetId: 8588
          revision: 1
          datasource: Prometheus
        Cluster-Monitoring-for-Kubernetes:
          gnetId: 10000
          revision: 1
          datasource: Prometheus
        Cluster-cost:
          gnetId: 8670
          revision: 5
          datasource: Prometheus
        Cluster-Dashboard:
          gnetId: 11358
          revision: 1